### ISSUE TITLE
Test with ESP IDF versions >5.0.1

### ISSUE THREAD

**Issue by nonument** [esp32-open-mac/esp32-open-mac#10]
Hello!

Me (and a group of volunteers from Summer of Nix) have made good progess packaging esp32-open-mac with Nix. The build process was extremely smooth (thank you!), the only issue we noticed was the pinned year-old release of ESP IDF gated with an `#error`: https://github.com/esp32-open-mac/esp32-open-mac/blob/e1453d72e5ff4e4351c667f38b0e58c7caea2df8/main/main.c#L17-L19

This is not a blocker for us, but as new ESP IDF releases are cut, our build configurations will continue drift further.

**Comment by redfast00** [comment]
Hm, I don't entirely like that you packaged this without communicating beforehand; I don't want to get support requests from people with broken/old builds (I don't know how Nix works and if that is possible). Can you link to your work?

The release of ESP IDF is indeed pinned at the moment because of the reason explained in the `#error` directive; every ESP IDF release, the binary blobs are also updated. Feel free to test if it still works with newer releases; eventually, we will implement the init ourselves, so there won't be a dependency on the binary blobs anymore and we'll be free to change ESP IDF versions.
