### ISSUE TITLE
Why ESP32?

### ISSUE THREAD

**Issue by par5er** [esp32-open-mac/esp32-open-mac#3]
This project is really exciting! Why did you choose to reverse the original ESP32, which is now superseded by ESP32S2/3?

Also, why the S class at all? Why not the C class which runs on RISC-V and thus should be easier to reverse in Ghidra?

– Dev

**Comment by lcgamboa** [comment]
Regarding the use of RISCV, I also share the @par5er's idea https://github.com/espressif/qemu/pull/80#issuecomment-1848396022

**Comment by chrysn** [comment]
To ease navigation of this kind of discussions, it would be useful to have (ideally, point to) an overview of which chip series use which WiFi (or other radio, considering #2) cores. This would allow users who'd like to use and advance this to get a better decision base for how hard which devices would be to add in here.

(I for myself do consider getting an ESP32 after years of shunning that platform due to its blobs, but so far have a hard time making an informed guess of whether the RISCV ones I'd fancy would "just" need some memory mapped peripheral addresses tuned, or would kick off a parallel project of its own).

**Comment by redfast00** [comment]
> Why ESP32?

When I started this project, there was a QEMU fork with very basic support for the wifi hardware for the ESP32; but not for other variants (or for RISC-V chips). I built further on the QEMU fork and built my own tooling to reverse engineer (for example the register access execution tracing).  The reason for continuing with the ESP32 instead of throwing away the code and starting anew with the C variants might seem like a sunk cost fallacy, but I don't think it is: I'd rather first have a fully functioning wifi implementation on one chip, than have 2 half efforts on two chips.

Xtensa is (or will in the next release be) supported in Ghidra natively, without plugins: see https://github.com/NationalSecurityAgency/ghidra/commit/7df3fd39c8d22d0425b3361e512e5b73a4637d27. While the quality of the decompiler/disassembler there might not be as good as the RISC-V one, I don't think that is a major reason to switch to the RISC-V chips.

The regular ESP32 also still seems to be the most popular chip, at least going by development boards. Does someone have statistics about the amount chips produced of each variety? The ESP32 is still in 'mass production', and not 'not recommended for new designs' (as per https://products.espressif.com/#/product-selector), so I don't think it's entirely correct to call it 'superseded'.

Don't get me wrong, it would be great to see an open source wifi implementation for the RISC-V chips, but me personally, I'll first focus on the regular ESP32.

As for:

> To ease navigation of this kind of discussions, it would be useful to have (ideally, point to) an overview of which chip series use which WiFi (or other radio, considering https://github.com/esp32-open-mac/esp32-open-mac/issues/2) cores. This would allow users who'd like to use and advance this to get a better decision base for how hard which devices would be to add in here.

Definitely! I don't have any information about this yet, I barely known anything about the wifi and radio cores in the regular ESP32. Once I have completely implemented enough of the radio init functionality, I'll have a look at how similar the regular ESP32 vs the other variants are.

**Comment by chrysn** [comment]
One data point I can provide from vimdiff'ing the output of nm on the various libphy.a in the esp-phy-lib repository is that the esp32 and esp32s2 PHY libs are relatively similar (maybe from the same C code with different ifdefs), whereas the esp32s3 looks more similar to the c variants (esp. esp32c2 and esp32c3; esp32c6 is yet a bit different).

I've tried doing some more concrete comparisons using [ghidriff](https://github.com/clearbluejar/ghidriff), but it barely manages to match anything even between esp32c2 and esp32c3, which indicates that those might be built with different compilers.
