### ISSUE TITLE
Investigate why `ping` reports duplicate packets

### ISSUE THREAD

**Issue by redfast00** [esp32-open-mac/esp32-open-mac#7]
```
64 bytes from 10.0.0.233: icmp_seq=1149 ttl=255 time=16.9 ms
64 bytes from 10.0.0.233: icmp_seq=1150 ttl=255 time=24.4 ms
64 bytes from 10.0.0.233: icmp_seq=1151 ttl=255 time=19.1 ms
64 bytes from 10.0.0.233: icmp_seq=1151 ttl=255 time=21.5 ms (DUP!)
64 bytes from 10.0.0.233: icmp_seq=1152 ttl=255 time=13.1 ms
64 bytes from 10.0.0.233: icmp_seq=1153 ttl=255 time=15.6 ms
64 bytes from 10.0.0.233: icmp_seq=1154 ttl=255 time=13.1 ms
64 bytes from 10.0.0.233: icmp_seq=1155 ttl=255 time=18.4 ms
64 bytes from 10.0.0.233: icmp_seq=1156 ttl=255 time=21.1 ms
64 bytes from 10.0.0.233: icmp_seq=1157 ttl=255 time=18.8 ms
64 bytes from 10.0.0.233: icmp_seq=1158 ttl=255 time=16.1 ms
64 bytes from 10.0.0.233: icmp_seq=1159 ttl=255 time=15.1 ms
64 bytes from 10.0.0.233: icmp_seq=1160 ttl=255 time=15.1 ms
64 bytes from 10.0.0.233: icmp_seq=1161 ttl=255 time=13.5 ms
64 bytes from 10.0.0.233: icmp_seq=1162 ttl=255 time=11.0 ms
64 bytes from 10.0.0.233: icmp_seq=1163 ttl=255 time=10.7 ms
64 bytes from 10.0.0.233: icmp_seq=1164 ttl=255 time=19.7 ms
64 bytes from 10.0.0.233: icmp_seq=1164 ttl=255 time=21.8 ms (DUP!)
64 bytes from 10.0.0.233: icmp_seq=1165 ttl=255 time=13.9 ms

```

**Comment by redfast00** [comment]
(this does not happen with the official ESP32 networking stack)

**Comment by rottaran** [comment]
Unicast frames are automatically retransmitted by the other wifi device. It can happen that your ESP is receiving the frame and you process it, but the HW-level ACK reply sent by your ESP is not successfully received by the other device. Hence, the other device sends the same frame again und receive it successfully a second time. In effect your ESP is answering the same ping request twice. 

The receiver side duplicate suppression is based on the sequence number in the 802.11 frame header. This number needs to be kept track of for each neighbor device. This is very likely not done by the hardware and has to be implemented in software. The simplest way is to just remember the last received sequence number for each neighbor and ignore all received frames that have the same number. 

However, I am not sure if a slight out of order delivery is possible because of the QoS things or the multiple TX slots. Also frame aggregation with selective retransmission would need to keep track of multiple nearby sequence numbers. A typical solution is a bitmask (for example 32bit) that slides along with the latest received sequence number and shows which frames were received before.


```
per neighbor device:
    uint32_t last_seqno;
    std::bitset<WINDOW_SIZE> seqno_bits;

int32_t seqno_diff = pkt->seqno - node.last_seqno;
if (seqno_diff <= 0 && seqno_diff > -WINDOW_SIZE) { // inside the window, slightly older
    if (node.seqno_bits[-seqno_diff] == true) => DUPLICATE
    node.seqno_bits[-seqno_diff] = true; // mark as seen before
} else if (seqno_diff > 0 && seqno_diff < WINDOW_SIZE) { // sequence number is slightly newer
    node.seqno_bits <<= seqno_diff; // advance the window
    node.seqno_bits[0] = true; // mark as seen before
    node.last_seqno = pkt->seqno; // remember head of the window
} else if (seqno_diff >= WINDOW_SIZE && seqno_diff < EXPECTED_SEQNO_RANGE) {
    // sequence number is much newer
    ESP_LOGI(TAG, "missed a lot of packets: %li", seqno_diff - 1);
    node.seqno_bits.reset();
    node.seqno_bits[0] = true; // mark as seen before
    node.last_seqno = pkt->seqno; // remember head of the window
} else { // received a much older packet
    ESP_LOGI(TAG, "other host may have restarted");
    node.seqno_bits.reset();
    node.seqno_bits[0] = true; // mark as seen before
    node.last_seqno = pkt->seqno; // remember head of the window
}
```

**Comment by redfast00** [comment]
Thanks for the extensive write-up @rottaran! I'll look into it :)

**Comment by Frostie314159** [comment]
@rottaran That's the likely cause, although the sequence number should increase with every frame transmitted and are set right before transmission. This shouldn't be affected by qos, since the seq num is set independently from the access category. I think a partial fix for this was delivered with block acks.

**Comment by redfast00** [comment]
Fixed in https://github.com/esp32-open-mac/esp32-open-mac/commit/e7c54f0550ca7b503db6ca557c59e8bf817a4a56

**Comment by rottaran** [comment]
I guess that all broadcast frames, not just the beacons, use that separate counter. The idea for the algorithm is likely old. I got it from the BATMAN mesh protocol in the Linux kernel, where it is used for duplicate suppression of flooding of broadcast payloads.
